//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ccct2019.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chitiethopdong
    {
        public int ID { get; set; }
        public string Tenchitiethopdong { get; set; }
        public Nullable<int> MauhopdongID { get; set; }
        public Nullable<int> BenAID { get; set; }
        public Nullable<int> BenBID { get; set; }
        public int IsActive { get; set; }
    
        public virtual BenA BenA { get; set; }
        public virtual BenB BenB { get; set; }
        public virtual Mauhopdong Mauhopdong { get; set; }
    }
}
