//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ccct2019.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ConnectDB : DbContext
    {
        public ConnectDB()
            : base("name=ConnectDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BenA> BenA { get; set; }
        public virtual DbSet<BenB> BenB { get; set; }
        public virtual DbSet<Canhan> Canhan { get; set; }
        public virtual DbSet<Chitiethopdong> Chitiethopdong { get; set; }
        public virtual DbSet<Congchungvien> Congchungvien { get; set; }
        public virtual DbSet<Doanhnghiep> Doanhnghiep { get; set; }
        public virtual DbSet<Donvi> Donvi { get; set; }
        public virtual DbSet<HopdongCCCT> HopdongCCCT { get; set; }
        public virtual DbSet<Hopdongkhac> Hopdongkhac { get; set; }
        public virtual DbSet<LoaiQH> LoaiQH { get; set; }
        public virtual DbSet<LoaiVBDVTH> LoaiVBDVTH { get; set; }
        public virtual DbSet<Mauhopdong> Mauhopdong { get; set; }
        public virtual DbSet<NganchanGiaitoa> NganchanGiaitoa { get; set; }
        public virtual DbSet<Nguoichungthuc> Nguoichungthuc { get; set; }
        public virtual DbSet<Permissions> Permissions { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
