//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ccct2019.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.NganchanGiaitoa = new HashSet<NganchanGiaitoa>();
            this.Permissions = new HashSet<Permissions>();
        }
    
        public int ID { get; set; }
        public string UserName { get; set; }
        public string PassWord { get; set; }
        public string Hoten { get; set; }
        public string Chucvu { get; set; }
        public Nullable<System.DateTime> Ngaysinh { get; set; }
        public string Sodienthoai { get; set; }
        public string Email { get; set; }
        public string Diachi { get; set; }
        public string Avatar { get; set; }
        public Nullable<int> Donvi { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int IsAdmin { get; set; }
        public int IsActive { get; set; }
    
        public virtual Donvi Donvi1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NganchanGiaitoa> NganchanGiaitoa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Permissions> Permissions { get; set; }
    }
}
